# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x, 1.20.x, 1.21.x]
        os: [ubuntu-latest, windows-latest, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go/Go+
      uses: goplus/setup-goplus@v1.1.0
      with:
        go-version: ${{ matrix.go-version }}
        gop-version: "main"
        check-latest: true
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Run testcases
      run: go test -v -coverprofile="coverage.txt" -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v3
